#!/usr/bin/env python3

import sys

if sys.argv[2] == '+':
	print(int(sys.argv[1]) + int(sys.argv[3]))

if sys.argv[2] == '-':
	print(int(sys.argv[1]) - int(sys.argv[3]))

if sys.argv[2] == '/':
	print(int(sys.argv[1]) / int(sys.argv[3]))

if sys.argv[2] == 'x':
	print(int(sys.argv[1]) * int(sys.argv[3]))